// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A class that exposes the [FirebaseOptions] for configuring Firebase.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObwILkCOgiFin-wn1lhsSvfVwa4dXsBA',
    appId: '1:38589617980:web:7a7ad670eb55238cdc3039',
    messagingSenderId: '38589617980',
    projectId: 'flutterfmu',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObwILkCOgiFin-wn1lhsSvfVwa4dXsBA',
    appId: '1:38589617980:android:7a7ad670eb55238cdc3039',
    messagingSenderId: '38589617980',
    projectId: 'flutterfmu',
    storageBucket: 'flutterfmu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObwILkCOgiFin-wn1lhsSvfVwa4dXsBA',
    appId: '1:38589617980:ios:7a7ad670eb55238cdc3039',
    messagingSenderId: '38589617980',
    projectId: 'flutterfmu',
    storageBucket: 'flutterfmu.firebasestorage.app',
    iosBundleId: 'com.example.lojaflutter',
  );
}
